- meta:
    title: 'Half-baked idea: Java class matching'
    path:
      - 'half-baked'
      - 'java class match'
    mini: 'Java Class Match'
    pygment_style: 'darcula'

- - - copy
    - from: './*.java'
      to: './'

- - - readDOM
    - file: './java_class_match.html'
  - - inlineCodeDirectives
  - - wrapWithBoilerplate
  - - addPygmentCssRef
#  - - addCssRef
#    #- path: '/css/pygment-tango.css'
#    - path: '/css/pygment-paraiso-dark.css'
  - - absPathRebase
  - - writeHTML