- meta:
     title: 'Short story: Reconciliation'
     path: ['reconciliation']
     mini: 'Reconciliation'

# copy assets
- - - copy
    - from: './*.png'
      to: './'
- - - copy
    - from: './lossless'
      to: './'

# build HTML
- - - readDOM
    - file: './reconciliation.html'
  - - wrapWithBoilerplate
    - hide_title: true
  - - readTxt
    - file: './style.css'
  - - mergeCSSIntoPage
  - - addCssRef
    - path: '/css/google-doc-insert.css'
  - - absPathRebase
  - - writeHTML
    - file: './reconciliation.html'