# copy assets
- - - copy
    - from: './*.png'
      to: './'
- - - copy
    - from: './lossless'
      to: './'

# simple copy
- - - readDOM
    - file: './reconciliation.html'
  - - absPathRebase
  - - writeHTML