- meta:
    title: 'Why is it so hard to do things?'
    path: ['do']
    mini: 'Do'
- - - copy
    - from: './*.jpg'
      to: './'
- - - readDOM
    - file: './do.html'
  - wrapWithBoilerplate
  - writeHTML