- meta:
    title: 'Why is it so hard to do things?'
    path: ['do']
    mini: 'Do'

# copy images
- - - copy
    - from: './*.jpg'
      to: './'

# build the primary do.html
- - - readDOM
    - file: './do.html'
  - - wrapWithColumn
    - column_class: col-5uw
  - - wrapWithBoilerplate
  - - writeHTML