- meta:
    title: 'Formatting large expressions'
    path: ['formatting large expressions']
    mini: 'Large Expressions'
    pygment_style: 'darcula'

- - - copy
    - from: './*.png'
      to: './'

- - - compressImages
    - glob: './*.png'
      width: 240
      quality: 85

- - - readDOM
    - file: './parenthesis.html'
  - - wrapWithColumn
    - column_class: inner-col
  - - fmtCodePreBlocks
  - - wrapWithBoilerplate
  - - addPygmentCssRef
  - - absPathRebase
  - - writeHTML